
named_list(yellow,[samaypurBadli,
	rohiniSector18,
	haiderpur,
	jahangirpuri,
	adarshNagar,
	azadpur,
	modelTown,
	guruTeghBahadurNagar,
	vishwaVidyalaya,
	vidhanSabha,
	civilLines,
	kashmereGate,
	chandniChowk,
	chawriBazar,
	newDelhi,
	rajivChowk,
	patelChowk,
	centralSecretariat,
	udyogBhawan,
	lokKalyanMarg,
	jorbagh,
	dilliHaatINA,
	aiims,
	greenPark,
	hauzKhas,
	malviyaNagar,
	saket,
	qutabMinar,
	chhatarpur,
	sultanpur,
	ghitorni,
	arjanGarh,
	guruDronacharya,
	sikandarpur,
	mgRoad,
	iffcoChowk,
	hudaCityCentre]).
named_list(green,[inderlok,
	ashokParkMain,
	punjabiBagh,
	shivajiPark,
	madipur,
	paschimViharEast,
	paschimViharWest,
	peeraGarhi,
	udyogNagar,
	maharajaSurajmalStadium,
	nangloi,
	nangloiRailwayStation,
	rajdhaniPark,
	mundka,
	mundkaIndustrialArea,
	ghevra,
	tikriKalan,
	tikriBorder,
	panditShreeRamSharma,
	bahadurgarhCity,
	brigadierHoshiyarSingh]).
named_list(pink,[majlisPark,
  	azadpur,
  	shalimarBagh,
  	netajiSubhashPlace,
  	shakurpur,
  	punjabiBaghWest,
  	esiBasaiDarapur,
  	rajouriGarden,
  	mayaPuri,
  	narainaVihar,
  	delhiCantt,
  	durgabaiDeshmukhSouthCampus,
  	sirVishweshwaraiahMotiBagh,
  	bhikajiCamaPlace,
  	dilliHaatINA,
  	southExtension,
  	lajpatNagar,
  	vinobapuri,
  	ashram,
  	saraiKaleKhanHazratNizamuddin,
  	mayurVihar1,
  	mayurViharPocket1,
  	trilokpuriSanjayLake,
  	vinodNagarEast,
  	mandawali,
  	ipExtension,
  	anandVihar,
  	karkarduma,
  	karkardumaCourt,
  	krishnaNagar,
  	eastAzadNagar,
  	welcome,
  	jaffrabad,
  	maujpur,
  	gokulpuri,
  	johriEnclave,
  	shivVihar]).

named_list(blue,[dwarkaSector21,
      dwarkaSector8,
      dwarkaSector9,
      dwarkaSector10,
      dwarkaSector11,
      dwarkaSector12,
      dwarkaSector13,
      dwarkaSector14,
      dwarka,
      dwarkaMor,
      nawada,
      uttamNagarWest,
      uttamNagarEast,
      janakPuriWest,
      janakPuriEast,
      tilakNagar,
      subhashNagar,
      tagoreGarden,
      rajouriGarden,
      rameshNagar,
      motiNagar,
      kirtiNagar,
      shadipur,
      patelNagar,
      rajendraPlace,
      karolBagh,
      jhandewalan,
      rkAshramMarg,
      rajivChowk,
      barakhamba,
      mandiHouse,
      supremeCourt,
      indraprastha,
      yamunaBank,
      akshardham,
      mayurVihar1,
      mayurViharExtention,
      newAshokNagar,
      noidaSector15,
      noidaSector16,
      noidaSector18,
      botanicalGarden,
      golfCourse,
      noidaCityCenter,
      noidaSector34,
      noidaSector52,
      noidaSector61,
      noidaSector59,
      noidaSector62,
      noidaElectronicCity]).
named_list(magenta,[janakPuriWest,
	dabriMor,
	dashrathPuri,
	palam,
	sadarBazaarCantonment,
	terminal1IGIAirport,
	shankarVihar,
	vasantVihar,
	munirka,
	rkPuram,
	iitDelhi,
	hauzKhas,
	panchsheelPark,
	chiragDelhi,
	greaterKailash,
	nehruEnclave,
	kalkajiMandir,
	okhlaNSIC,
	sukhdevVihar,
	jamiaMilliaIslamia,
	okhlaVihar,
	jasolaViharShaheenBagh,
	kalindiKunj,
	okhlaBirdSanctuary,
	botanicalGarden]).
named_list(greenbranch,[ashokParkMain,
  	satguruRamsinghMarg,
  	kirtiNagar]).
named_list(orange,[newDelhi,
	shivajiStadium,
	dhaulaKuan,
	delhiAerocity,
	igiAirport,
	dwarkaSector21]).
named_list(bluebranch,[yamunaBank,
  	laxmiNagar,
  	nirmanVihar,
  	preetVihar,
  	karkarduma,
  	anandVihar,
  	kaushambi,
  	vaishali]).
named_list(grey,[dwarka,
      nangli,
      najafgarh]).
named_list(red,[shaheedSthal,
     hindonRiver,
     arthala,
     mohanNagar,
     shyamPark,
     majorMohitSharma,
     rajBagh,
     shaheedNagar,
     dilshadGarden,
     jhilMil,
     mansaroverPark,
     shahdara,
     welcome,
     seelampur,
     shastriPark,
     kashmereGate,
     tisHazari,
     pulBangash,
     pratapNagar,
     shastriNagar,
     inderlok,
     kanhaiyaNagar,
     keshavPuram,
     netajiSubhashPlace,
     kohatEnclave,
     pitamPura,
     rohiniEast,
     rohiniWest,
     rithala]).
named_list(violet,[kashmereGate,
	lalQuila,
	jamaMasjid,
	delhiGate,
	ito,
	mandiHouse,
	janpath,
	centralSecretariat,
	khanMarket,
	jawaharlalNehruStadium,
	jangpura,
	lajpatNagar,
	moolchand,
	kailashColony,
	nehruPlace,
	kalkajiMandir,
	govindPuri,
	okhla,
	jasola,
	saritaVihar,
	mohanEstate,
	tughlakabad,
	badarpurBorder,
	sarai,
	nhpcChowk,
	mewalaMaharajpur,
	sector28Faridabad,
	badkalMor,
	oldFaridabad,
	neelamChowkAjronda,
	bataChowk,
	escortsMujesar,
	santSurdasSihi,
	rajaNaharSingh]).

adjacent_mem(E,F,[E, F|_]).
adjacent_mem(E,F,[_|L]) :- adjacent_mem(E,F,L).


node(A,Name) :- named_list(Name,L),member(A,L).
edges(A,B,Name) :- named_list(Name,L),adjacent_mem(A,B,L).

connected(node(X,I),node(X,K)):-node(X,I),node(X,K).
connected(node(X,Z),node(Y,Z)) :- edges(X,Y,Z) ; edges(Y,X,Z).


len([],0).
len([H|T],N) :- len(T,R),N is R+1.

conv(node(A,B),(B,A)).

ml([],Z,Z).
ml([node(A,B)|T],Z,Acc) :- conv(node(A,B),Y),ml(T,Z,[Y|Acc]).


shortestpath(Source,Destination, Answer) :-
  bfs([[node(Source,X)]],Destination, Answer),node(Source,X).

bfs([[node(Destination,B)|Path]|_],Destination, [node(Destination,B)|Path]) :- node(Destination,B).

bfs([Path|Paths],Destination, Answer) :-
						  extension(Path, NewPaths),
						  append(Paths, NewPaths, Paths1),
						  bfs(Paths1,Destination, Answer).

extension([Node|Path], NewPaths) :-
										  findall([NewNode, Node|Path],
										          (connected(Node, NewNode),
										           not(member(NewNode,[Node|Path]))),
										          NewPaths),!.
extension(Path,[]).
smpath(A,B,N,Ans) :- spath(A,B,N,[],Ans).
spath(A,B,0,E,E).

spath(A,B,N,L,W) :- shortestpath(A,B,Z), not(member(Z,L)),spath(A,B,T,[Z|L],W),N is T+1.


doaction([],P,P).
doaction([H|T],P,K) :- ml(H,Z,[]),doaction(T,P,[Z|K]).

paths(A,B,LL) :- smpath(A,B,5,P),doaction(P,LL,[]).

getLengths([],Z,Z).
getLengths([H|T],Z,L):- len(H,R),getLengths(T,Z,[R|L]).
